### ISSUE TITLE
improved use of S4

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/quickPlot#5]
See recently updated https://adv-r.hadley.nz/s4:

- [ ] use constructors instead of `new()`:

    > It’s also possible to create an instance using `new()` and the name of the class. This is not recommended because it introduces some ambiguity. What happens if there are two packages that both define the `Person` class?

 
~~[ ] don't use `{` in generics:~~

   ~~> Note that it is bad practice to use `{` in the generic function. This triggers a special case that is more expensive, and generally best avoided.~~

- [ ] use of `setOldClass()`:

    >  If you’re trying to build an S4 class on top of a S3 class provided by a package, it is better to request that the package maintainer add this call to the package, rather than running it yourself.

**Comment by eliotmcintire** [comment]
I benchmarked the { in the setGeneric, and it seems to have a 0.6 microsecond cost, but that is hard to detect reliably, so it may be zero. I am happy to start omitting `{` in setGenerics, but there is no real need, based on speed to retroactively change this. I am removing from to do list.

**Comment by eliotmcintire** [comment]
Because of need to reduce package dependencies, we have moved away from method dispatch using S3 and S4 classes as we cannot dispatch on classes that are not imported. There are still methods, but mostly it is the default method that is defined here. Other packages can make other methods. We are now favouring S3 for its simplicity.
