### ISSUE TITLE
Plot() fails when object name contains symbol

### ISSUE THREAD

**Issue by ygc2l** [PredictiveEcology/quickPlot#6]
A small reprex:

```r
obj <- list("1" = raster(matrix(1:100, nrow = 10)))
Plot(obj[["1"]])
```

I will submit a PR with a fix.

**Comment by eliotmcintire** [comment]
This has been made obsolete under most conditions due to improvements upstream, using `deparse(substitute` with a serious tweak taken from [an answer here](https://stat.ethz.ch/pipermail/r-help/2011-January/265516.html) and the new function  `whereInStack` that does a much better job at finding the environment in the call stack. These changes were made in 84a30f69824ac8a98d12895121ff4ea63b052898
